### ISSUE TITLE
Wacom tablets not working 

### ISSUE THREAD

**Issue by call911nowplz** [LUXTACO/Osussist#3]
Seems like the script works with a mouse but it doesn't work with a tablet
The script seems to "try" moving the cursor and you can see a small jittering motion. But the tablet pen keeps the cursor from moving

Using the default Wacom driver

**Comment by LUXTACO** [comment]
It's not made for tablets, mainly because I don't own one, BUT I'm looking forward to adding tablet support in the future IF the repo gains enough popularity
