### ISSUE TITLE
winerror 87

### ISSUE THREAD

**Issue by userUIX** [LUXTACO/Osussist#4]
![Screenshot_3](https://github.com/LUXTACO/Osussist-External-AimAssist/assets/49812381/a5dfb91c-c66d-42be-b8f1-c4b906391493)

**Comment by userUIX** [comment]
how to fix?

**Comment by LUXTACO** [comment]
What is your python version?

**Comment by userUIX** [comment]
> What is your python version?

3.12.2

**Comment by LUXTACO** [comment]
It might be something to do with your pc, try to reinstall python, or reinstalling the libs

**Comment by userUIX** [comment]
> It might be something to do with your pc, try to reinstall python, or reinstalling the libs

it didn't help(

**Comment by LUXTACO** [comment]
umm, try to put it in a venv

**Comment by LUXTACO** [comment]
It has to do with your python architecture, it should be x64 not x32
